"""
emailer.py — Gmail SMTP email sender for HealthBridge
Sends the health summary CSV to the doctor's email address.
Uses Gmail App Passwords (does NOT require OAuth — just a 16-char app password).

Setup:
  1. Go to https://myaccount.google.com/apppasswords
  2. Create an app password for "HealthBridge"
  3. Enter the 16-char password in the app settings
"""

import smtplib
import io
import csv
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from typing import Optional


def build_csv_content(garmin: Optional[dict], peloton: Optional[dict], date_start: str, date_end: str) -> str:
    """Build the CSV string from combined health data."""
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow(["HealthBridge Health Report"])
    writer.writerow(["Generated", datetime.now().strftime("%B %d, %Y at %I:%M %p")])
    writer.writerow(["Date Range", f"{date_start} to {date_end}"])
    writer.writerow([])

    if garmin:
        writer.writerow(["=== GARMIN METRICS ==="])
        g = garmin
        rows = [
            ["Resting Heart Rate (avg)", _fmt(g.get("heart_rate", {}).get("resting_avg")), "bpm"],
            ["HRV (avg)", _fmt(g.get("heart_rate", {}).get("hrv_avg")), "ms"],
            ["SpO2 (avg)", _fmt(g.get("spo2", {}).get("avg")), "%"],
            ["Stress Score (avg)", _fmt(g.get("stress", {}).get("avg_score")), "/100"],
            ["Body Battery Peak (avg)", _fmt(g.get("body_battery", {}).get("avg_peak")), ""],
            ["Daily Steps (avg)", _fmt(g.get("steps", {}).get("daily_avg")), "steps"],
            ["Total Steps", _fmt(g.get("steps", {}).get("total")), "steps"],
            ["Sleep Score (avg)", _fmt(g.get("sleep", {}).get("score_avg")), "/100"],
            ["Deep Sleep (avg)", _fmt(g.get("sleep", {}).get("deep_hours_avg")), "hrs"],
            ["REM Sleep (avg)", _fmt(g.get("sleep", {}).get("rem_hours_avg")), "hrs"],
            ["Light Sleep (avg)", _fmt(g.get("sleep", {}).get("light_hours_avg")), "hrs"],
            ["Awake Time (avg)", _fmt(g.get("sleep", {}).get("awake_hours_avg")), "hrs"],
            ["Weight", _fmt(g.get("weight", {}).get("weight_lbs") if g.get("weight") else None), "lbs"],
            ["BMI", _fmt(g.get("weight", {}).get("bmi") if g.get("weight") else None), ""],
        ]
        for row in rows:
            writer.writerow(row)
        writer.writerow([])

    if peloton and peloton.get("workouts"):
        workouts = peloton["workouts"]
        total_output = sum(w.get("total_output_kj") or 0 for w in workouts)
        hr_vals = [w["avg_heart_rate"] for w in workouts if w.get("avg_heart_rate")]
        avg_hr = round(sum(hr_vals) / len(hr_vals)) if hr_vals else None

        writer.writerow(["=== PELOTON SUMMARY ==="])
        writer.writerow(["Total Workouts", len(workouts)])
        writer.writerow(["Total Output", _fmt(total_output), "kJ"])
        writer.writerow(["Avg Heart Rate (workouts)", _fmt(avg_hr), "bpm"])
        writer.writerow([])

        writer.writerow(["--- WORKOUT LOG ---"])
        writer.writerow(["Date", "Type", "Class Title", "Instructor", "Duration (min)", "Output (kJ)", "Avg HR (bpm)", "Calories", "Distance (mi)"])
        for w in workouts:
            writer.writerow([
                w.get("date", ""),
                w.get("type", ""),
                w.get("title", ""),
                w.get("instructor", ""),
                w.get("duration_minutes", ""),
                w.get("total_output_kj", ""),
                w.get("avg_heart_rate", ""),
                round(w.get("calories") or 0) or "",
                w.get("distance_miles", ""),
            ])

    return output.getvalue()


def send_health_report(
    gmail_user: str,
    gmail_app_password: str,
    doctor_email: str,
    patient_name: str,
    garmin_data: Optional[dict],
    peloton_data: Optional[dict],
    date_start: str,
    date_end: str,
) -> dict:
    """
    Send the health report CSV to the doctor via Gmail.
    Returns {"success": True} or {"success": False, "error": "..."}
    """
    try:
        csv_content = build_csv_content(garmin_data, peloton_data, date_start, date_end)
        filename = f"health-report-{date_start}-to-{date_end}.csv"

        # Build email
        msg = MIMEMultipart()
        msg["From"] = gmail_user
        msg["To"] = doctor_email
        msg["Subject"] = f"Health Report — {patient_name} ({date_start} to {date_end})"

        body = f"""Hello,

Please find attached the automated health report for {patient_name}, covering {date_start} to {date_end}.

This report was generated by HealthBridge and includes:
• Garmin Connect data: resting heart rate, HRV, SpO2, sleep score/stages, stress, body battery, steps, weight/BMI
• Peloton workout history: workout type, duration, output, heart rate, calories

Report generated: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}

—
Sent automatically by HealthBridge
"""
        msg.attach(MIMEText(body, "plain"))

        # Attach CSV
        attachment = MIMEBase("application", "octet-stream")
        attachment.set_payload(csv_content.encode("utf-8"))
        encoders.encode_base64(attachment)
        attachment.add_header("Content-Disposition", f'attachment; filename="{filename}"')
        msg.attach(attachment)

        # Send via Gmail SMTP
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_user, gmail_app_password)
            server.sendmail(gmail_user, doctor_email, msg.as_string())

        return {"success": True, "sent_to": doctor_email, "filename": filename}

    except smtplib.SMTPAuthenticationError:
        return {"success": False, "error": "Gmail authentication failed. Check your App Password."}
    except Exception as e:
        return {"success": False, "error": str(e)}


def _fmt(val):
    if val is None:
        return ""
    if isinstance(val, float):
        return round(val, 1)
    return val
